version: '3.7'

services:
  vault-server:
    image: 'vault:1.9.3'
    container_name: 'vault-server'
    command: 'server'
    privileged: 'true'
    restart: 'always'
    cap_add:
    - 'IPC_LOCK'
    environment:
    - 'VAULT_ADDR=http://127.0.0.1:8200'
    volumes:
    - './config:/vault/config'
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.vault.rule=Host(`vault.docker.localhost`)'
    - 'traefik.http.routers.vault.tls=true'
    - 'traefik.http.services.vault.loadbalancer.server.scheme=http'
    - 'traefik.http.services.vault.loadbalancer.server.port=8200'
    networks:
      public:

networks:
  public:
    external: true
