version: '3.7'

services:
  traefik:
    image: 'traefik:v2.6.0'
    container_name: traefik
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    networks:
      public:

networks:
  public:
    external: true